from pathlib import Path
p=Path('roguelite-planning/studio-prototype/combat/InstallKatana.luau')
s=p.read_text().replace('CFrame.Angles(0,0,-.97)','CFrame.Angles(0,0,.97)').replace('Vector3.new(-.51046747,-2.2885015,0)','Vector3.new(.51046747,-2.2885015,0)').replace('Vector3.new(.344366,2.383546,0)','Vector3.new(-.344366,2.383546,0)')
s=s.replace('p.CFrame=CFrame.Angles','p.PivotOffset=CFrame.identity;p.CFrame=CFrame.Angles')
s=s.replace("remote.Name=name;remote.Parent=package", "remote.Name=name;remote.Sandboxed=true;remote.Capabilities=SecurityCapabilities.new(Enum.SecurityCapability.Basic,Enum.SecurityCapability.RemoteEvent);remote.Parent=package")
p.write_text(s)
p=Path('roguelite-planning/studio-prototype/combat/measure_katana.py');s=p.read_text().replace('Vector((a.x,a.z,-a.y))','Vector((-a.x,a.z,a.y))').replace("Matrix.Rotation(-.97,3,'Z')","Matrix.Rotation(.97,3,'Z')");p.write_text(s)
p=Path('roguelite-planning/FLOATING_WEAPON_PRESENTATION.md');s=p.read_text().replace('The formation does not continuously spin by default. Dedicated orbital weapons may still circle as their attack behavior.','Weapons occupy assigned floating slots. The formation does not spin 360 degrees around the avatar. Any earlier orbital-weapon concepts must be reconciled with this fixed-slot rule before implementation.')
s=s.replace('2. Prototype a floating Glock with independent auto-aim, muzzle firing and recoil against the existing zombies.','2. Prototype the katana first using the user-resized play-size display model: fixed right-hand-side floating slot, independent auto-targeting, windup/slash/recovery, server damage, and damage numbers.')
s=s.replace('3. Add one thrust/swing weapon and test mixed asynchronous attacks before expanding to the full roster.','3. Tune katana reach, cadence, clearance, and hit feedback; then add a ranged weapon and test mixed asynchronous attacks before expanding to the full roster.')
s+='\n## Confirmed clearance and test controls — 2026-09-17\n\nWeapon geometry must stay outside the avatar throughout idle, aiming, windup, strike, and recovery. A weapon behind or beside the player must never take a shortcut through the avatar to attack an enemy in front. Use an outward route with clearance or skip an unsafe/unreachable target. The katana prototype protects the entire visible mesh with a capsule around the sword and a clearance cylinder around the avatar. It returns to its assigned slot after each slash, rather than orbiting. Server-confirmed hits show the actual damage amount above the enemy.\n\nStudio test buttons/keys: Zombies [Z] removes the active wave and respawns five when re-enabled; Katana [K] hides the weapon and stops attacks. These are separate toggles. Test controls are Studio-only, grant no persistent rewards, and are validated on the server. See studio-prototype/combat/README.md for prototype tuning and validation.\n'
p.write_text(s)
p=Path('roguelite-planning/MASTER_GAME_DESIGN.md');s=p.read_text().replace('**Version:** 0.32 — visible floating auto-attacking weapons','**Version:** 0.33 — fixed weapon slots and katana combat prototype').replace('Default floating formation is not constant orbiting; dedicated orbitals may circle.','Weapons occupy specific assigned floating slots; they do not spin 360 degrees around the avatar. Earlier orbital concepts require review against this rule.')
s=s.replace('Start with waist-to-chest-height placement and tune readability in Studio.','Start with waist-to-chest-height placement and tune readability in Studio. Weapon geometry must never pass through the avatar during idle or any attack phase. A rear/side weapon must take a clear outward attack path or wait for a reachable target; it must not slash through the player to reach a front enemy. Each confirmed enemy hit displays the actual damage amount above that enemy.')
s+='\n### Katana combat prototype — 2026-09-17\n\nFirst weapon implementation uses the katana at the user-adjusted play-size display scale, in a fixed right-side slot. Automatic outward slashes damage zombies on the server and display floating damage numbers. Studio-only Zombies [Z] and Katana [K] toggles independently control the wave and weapon. Initial tuning: 25 damage, 1.05-second attack cadence, 100-health zombies, three-second replacement after a kill. These are prototype values for testing. Details and limitations: [Combat prototype](studio-prototype/combat/README.md).\n'
p.write_text(s)
p=Path('roguelite-planning/CURRENT_GAME_STRUCTURE.md');s=p.read_text().replace('They do not all continuously orbit; dedicated orbital weapons may circle.','Each weapon has an assigned floating slot; the formation does not rotate 360 degrees around the avatar. Attacks must preserve avatar clearance and show damage numbers for confirmed enemy hits.');p.write_text(s)
